proxy_cache_path /var/cache/nginx/snapgram levels=1:2 keys_zone=snapgram_media:10m max_size=1g inactive=30m use_temp_path=off;

server {
    listen 80;

    location /snapgram-media/ {
        proxy_cache snapgram_media;
        proxy_cache_valid 200 302 10m;
        proxy_cache_valid 404 1m;
        proxy_ignore_headers Cache-Control;
        add_header X-Cache $upstream_cache_status always;

        rewrite ^/snapgram-media/(.*)$ /snapgram-media/$1 break;
        proxy_pass http://minio:9000;
        proxy_set_header Host minio:9000;
    }
}

